#!/bin/bash
#PBS -N thesisS.b01
#PBS -q devel
#PBS -W group_list=g26209
#PBS -l select=4:ncpus=10:model=ivy
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -m abe

module load comp-intel/2020.4.304
module load mpi-hpe/mpt.2.25
module load hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

export RUN_DIR=/nobackupp11/mpoinell/meltchannels/run00b

cd $RUN_DIR
mpiexec -np 40 ./mitgcmuv_meltchannels
